virustotal_api_key: "addb6c3d42a213fe325f5dd4d9417122dc2f4173d6fbba565da937737b6cf9e6"
keytaro_api_key: "a36c2927f5f3b8b2b8e8bdc3c3dcd6a1"
keitaro_url: "https://phonicalzl.com/admin_api/v1"
telegram_bot_token: "8568517204:AAFIWW5jbnvpkVsh6_8OvqTLm9_eImn53AE"